import asyncio
from agents import Runner, trace
from ai_agents import manager_agent


async def main():
    print("Starting SDR Email Generation Pipeline")
    
    with trace("SDR Pipeline"):
        message = "send cold sales email generated by the tools to dear ceo"
        print(f"User Request: {message}")
        
        response = await Runner.run(manager_agent, message)
        
        print("Pipeline Execution Complete")

asyncio.run(main())