import asyncio
from agents import Runner, trace
from ai_agents import manager_agent


async def main():
    with trace("SDR Pipeline"):
        message = "send cold sales email generated by the tools to dear ceo"
        response = await Runner.run(manager_agent, message)

asyncio.run(main())